### ISSUE TITLE
Display missing pathway information about reactions

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#145]
Complete once https://github.com/KarrLab/datanator_rest_api/issues/33 is finished.

**Comment by jonrkarr** [comment]
This appears to be almost done except the reaction pages often don't display pathways. E.g., http://localhost:3000/reaction/D-Glucose%201-phosphate--%3ED-Glucose%206-phosphate/Colibacter doesn't play any pathways although KEGG shows 4 pathways https://www.genome.jp/dbget-bin/www_bget?ec:5.4.2.8.

**Comment by lzy7071** [comment]
> This appears to be almost done except the reaction pages often don't display pathways. E.g., http://localhost:3000/reaction/D-Glucose%201-phosphate--%3ED-Glucose%206-phosphate/Colibacter doesn't play any pathways although KEGG shows 4 pathways https://www.genome.jp/dbget-bin/www_bget?ec:5.4.2.8.

This is from my end. I was filling in `kegg_meta` fields for all the documents in `sabio_rk` collection but the operation timed out half way through. I started the second half of the filling operation. The problem should resolve itself once that is done.

**Comment by lzy7071** [comment]
See [#209 ](https://github.com/KarrLab/datanator_frontend/issues/209#issuecomment-605686120) for further comments.

**Comment by jonrkarr** [comment]
Some reactions still don't display pathways e.g., http://localhost:3000/reaction/D-Glucose%201-phosphate--%3ED-Glucose%206-phosphate/Colibacter. @lzy7071 should the pathway information be returned by the RES API now?

**Comment by lzy7071** [comment]
> Some reactions still don't display pathways e.g., http://localhost:3000/reaction/D-Glucose%201-phosphate--%3ED-Glucose%206-phosphate/Colibacter. @lzy7071 should the pathway information be returned by the RES API now?

Looking into it now.

**Comment by lzy7071** [comment]
> > Some reactions still don't display pathways e.g., http://localhost:3000/reaction/D-Glucose%201-phosphate--%3ED-Glucose%206-phosphate/Colibacter. @lzy7071 should the pathway information be returned by the RES API now?
> 
> Looking into it now.

Instead of relying on `kegg_meta` in documents, it will now look up kegg ortholog information directly from `kegg_orthologg` collection in MongoDB. The link should have pathway information within`kegg_meta` object once the latest API is deployed.

**Comment by jonrkarr** [comment]
This seems to be fixed.
